### PR TITLE
Add Examples

### PR DESCRIPTION
**Pull request by DerTee**
This PR adds 13 examples ported from Raylib.
Since creating one Beef project per example to get an .exe per example would clutter the IDE workspace, I opted for a single example project, which produces one launcher .exe used to start all the examples:
raylib-beef-examples-launcher_2021-11-26_21-56-48

This launcher needs some more work, but for now it does its job, imho.

### Known issues
The launcher has one annoying bug: After starting the first example and closing it, the launcher window starts again and now you have to click once, which does nothing at all, after that you can click any of the other examples to start them.
That seems to be related to raylib's internal state handling of Input events.
Launching two separate raylib instances, one for the launcher, one for the example sadly does not work, because raylib doesn't support that (at least not the way I tried to do it).
I currently have no idea for a quick fix, because I think this really should be handled by C raylib itself.

### CODE REVIEW

**Comment by M0n7y5** [comment]
Examples should be in different repository imho. I don't wanna bloat my library by examples.

**Comment by DerTee** [comment]
I thought about making it a different repo for the same reason as you (to not add bloat), but having it all in one place, no version mismatch etc. has its benefits, too (also Raylib does it that way, it's all in one).
Since you prefer a separate repo I'm happy to create a one.
I'll write here when done.

**Comment by DerTee** [comment]
The repo for the examples is at https://github.com/DerTee/raylib-beef-examples

A link to it in the raylib-beef Readme would be useful nice, but I think you should fork the examples and link to your own fork instead, just so everything is under one account, not scattered through multiple ones.

From my side the PR can be closed.

**Comment by M0n7y5** [comment]
Added link to example to readme in 3365df6

**Pull request closed without merging**
